apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.cert.name }}
  namespace: {{ .Values.cert.namespace }}
spec:
  secretName: {{ .Values.cert.secretname }}
  dnsNames:
  - {{ .Values.cert.dnsname }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
